window.esdocSearchIndex = [
  [
    "blitzr-js-sdk/src/blitzr.js~blitzr",
    "class/src/blitzr.js~Blitzr.html",
    "<span>Blitzr</span> <span class=\"search-result-import-path\">blitzr-js-sdk/src/blitzr.js</span>",
    "class"
  ],
  [
    "blitzr-js-sdk/src/player.js~player",
    "class/src/player.js~Player.html",
    "<span>Player</span> <span class=\"search-result-import-path\">blitzr-js-sdk/src/player.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/blitzr.js",
    "file/src/blitzr.js.html",
    "src/blitzr.js",
    "file"
  ],
  [
    "src/blitzr.js~blitzr#artist",
    "class/src/blitzr.js~Blitzr.html#instance-member-artist",
    "src/blitzr.js~Blitzr#artist",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#constructor",
    "class/src/blitzr.js~Blitzr.html#instance-constructor-constructor",
    "src/blitzr.js~Blitzr#constructor",
    "method"
  ],
  [
    "src/blitzr.js~blitzr#event",
    "class/src/blitzr.js~Blitzr.html#instance-member-event",
    "src/blitzr.js~Blitzr#event",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#harmonia",
    "class/src/blitzr.js~Blitzr.html#instance-member-harmonia",
    "src/blitzr.js~Blitzr#harmonia",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#key",
    "class/src/blitzr.js~Blitzr.html#instance-get-key",
    "src/blitzr.js~Blitzr#key",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#key",
    "class/src/blitzr.js~Blitzr.html#instance-set-key",
    "src/blitzr.js~Blitzr#key",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#label",
    "class/src/blitzr.js~Blitzr.html#instance-member-label",
    "src/blitzr.js~Blitzr#label",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#radio",
    "class/src/blitzr.js~Blitzr.html#instance-member-radio",
    "src/blitzr.js~Blitzr#radio",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#release",
    "class/src/blitzr.js~Blitzr.html#instance-member-release",
    "src/blitzr.js~Blitzr#release",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#search",
    "class/src/blitzr.js~Blitzr.html#instance-member-search",
    "src/blitzr.js~Blitzr#search",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#shop",
    "class/src/blitzr.js~Blitzr.html#instance-member-shop",
    "src/blitzr.js~Blitzr#shop",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#tag",
    "class/src/blitzr.js~Blitzr.html#instance-member-tag",
    "src/blitzr.js~Blitzr#tag",
    "member"
  ],
  [
    "src/blitzr.js~blitzr#track",
    "class/src/blitzr.js~Blitzr.html#instance-member-track",
    "src/blitzr.js~Blitzr#track",
    "member"
  ],
  [
    "src/blitzr.js~blitzr.player",
    "class/src/blitzr.js~Blitzr.html#static-method-player",
    "src/blitzr.js~Blitzr.player",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/player.js",
    "file/src/player.js.html",
    "src/player.js",
    "file"
  ],
  [
    "src/player.js~player#constructor",
    "class/src/player.js~Player.html#instance-constructor-constructor",
    "src/player.js~Player#constructor",
    "method"
  ],
  [
    "src/player.js~player#currenttime",
    "class/src/player.js~Player.html#instance-get-currentTime",
    "src/player.js~Player#currentTime",
    "member"
  ],
  [
    "src/player.js~player#duration",
    "class/src/player.js~Player.html#instance-get-duration",
    "src/player.js~Player#duration",
    "member"
  ],
  [
    "src/player.js~player#load",
    "class/src/player.js~Player.html#instance-method-load",
    "src/player.js~Player#load",
    "method"
  ],
  [
    "src/player.js~player#pause",
    "class/src/player.js~Player.html#instance-method-pause",
    "src/player.js~Player#pause",
    "method"
  ],
  [
    "src/player.js~player#play",
    "class/src/player.js~Player.html#instance-method-play",
    "src/player.js~Player#play",
    "method"
  ],
  [
    "src/player.js~player#seekto",
    "class/src/player.js~Player.html#instance-method-seekTo",
    "src/player.js~Player#seekTo",
    "method"
  ],
  [
    "src/player.js~player#stop",
    "class/src/player.js~Player.html#instance-method-stop",
    "src/player.js~Player#stop",
    "method"
  ],
  [
    "src/player.js~player#volume",
    "class/src/player.js~Player.html#instance-set-volume",
    "src/player.js~Player#volume",
    "member"
  ],
  [
    "src/player.js~player#volume",
    "class/src/player.js~Player.html#instance-get-volume",
    "src/player.js~Player#volume",
    "member"
  ],
  [
    "src/xhr-browser.js",
    "file/src/xhr-browser.js.html",
    "src/xhr-browser.js",
    "file"
  ],
  [
    "src/xhr.js",
    "file/src/xhr.js.html",
    "src/xhr.js",
    "file"
  ]
]